# Generated by Django 3.2.16 on 2023-04-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20230404_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='compromised',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_opened',
            field=models.BooleanField(null=True),
        ),
    ]
