# Generated by Django 3.2.16 on 2023-04-05 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20230404_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200),
        ),
    ]
