# Generated by Django 3.2.16 on 2023-04-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20230405_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_reported',
            field=models.BooleanField(default=False),
        ),
    ]
