# Generated by Django 3.2.16 on 2023-04-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_user_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='click_date',
        ),
    ]
