# Generated by Django 3.2.16 on 2023-04-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_rename_date_user_click_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='compromised',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_reported',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_opened',
            field=models.IntegerField(default=0),
        ),
    ]
