# Generated by Django 3.2.16 on 2023-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20230420_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='compromised',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_opened',
            field=models.BooleanField(default=False),
        ),
    ]
